### PR TITLE
Feat: add export command to make output evaluable for shell

### PR DESCRIPTION
**Pull request by jynolen**
This PR follow #185 in order to allow people to evaluate content of envman store for shell.
It makes it easy to managed user profile environment variable.

Usage example:

`eval $(envman export [--expand] --format envlist)`

Here result of differents values

```
$ cat ~/.envstore.yml
envs:
- EXPAND: ${PWD}
- TEST_QUOTE: '"HYU"'
- TEST_QUOTE_EXPAND: '"$PWD"'
- TEST_QUOTE_EXPAND_1: '"${PWD}"'
- TEST_QUOTE_EXPAND_2: '"${TEST_QUOTE}"'

$ ./opensource/envman/main print --format envlist

export TEST_QUOTE_EXPAND="\"$PWD\""
export TEST_QUOTE_EXPAND_1="\"${PWD}\""
export TEST_QUOTE_EXPAND_2="\"${TEST_QUOTE}\""
export EXPAND="${PWD}"
export TEST_QUOTE="\"HYU\""


$ ./opensource/envman/main print --format envlist --expand

export EXPAND="/home/jynolen"
export TEST_QUOTE="\"HYU\""
export TEST_QUOTE_EXPAND="\"/home/jynolen\""
export TEST_QUOTE_EXPAND_1="\"/home/jynolen\""
export TEST_QUOTE_EXPAND_2="\"\"HYU\"\""


```

### CODE REVIEW

**Comment by jynolen** [comment]
Hello any news about this PR ?

**Comment by jynolen** [comment]
Friendly reminder

**Review by Whiskyller — APPROVED** [review]

**Review by ofalvai — APPROVED** [review]
LGTM, a simple addition! Thank you for the contribution @jynolen 💜

**Comment by KonradIT** [comment]
Very cool! Thanks!

**Pull request merged**
